version: '3.1'

services:
  db_guiafast:
    image: bitnami/mongodb:6.0.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
